name: Generate & Deploy
on: 
  push:
    branches: [page-src]

jobs:
  gen-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x

      - name: Install packages
        run: npm install
      - name: Generate Site
        run: npm run generate
      - name: Deploy Site
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: master
          FOLDER: dist
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
